---
# Used for adding apt repos and their signing keys if a package cannot be found in existing apt repositories
add_apt_repos:
  - package_name: code 
    key_url: https://packages.microsoft.com/keys/microsoft.asc
    key_filename: microsoft-archive-keyring.asc
    apt_repo_url: https://packages.microsoft.com/repos/code
    source_list_name: vscode
    sources_list_suite_name: stable
    sources_list_components: main

  - package_name: miktex 
    key_url: https://miktex.org/download/key
    key_filename: miktex.asc
    apt_repo_url: https://miktex.org/download/debian
    source_list_name: miktex
    sources_list_suite_name: ''       # defaults to ansible_distribution_release
    sources_list_components: universe

  - package_name: google-chrome-stable
    key_url: https://dl.google.com/linux/linux_signing_key.pub
    key_filename: google-chrome.asc
    apt_repo_url: https://dl.google.com/linux/chrome/deb/
    source_list_name: google-chrome
    sources_list_suite_name: stable
    sources_list_components: main

  # Remove any pre-installed apt packages
packages_to_remove:
  - gnome-games
  - libreoffice*

# Install user apt packages after removing and adding apt repos above 
packages_to_install:
  core:
    - sudo
    - curl
    - wget
    - bash-completion
    - linux-headers-amd64 # needed for future driver installations
    - software-properties-common # provides an easier way to edit entries in /etc/apt/sources.list
    - perl # needed for miktex installer, and likely for other software that need a perl interpreter
    - jq
  programming: 
    - git
    - code
    - python3
    - nodejs
    - npm
  school:
    - miktex
  gnome:
    - dconf-editor
    - gsettings
    - nautilus # default Gnome files app
    - nautilus-extension-gnome-terminal # adds show in terminal context menu
    - gnome-text-editor
    - baobab # Gnome disk usage analyzer. It's pretty cool
    - file-roller # Gnome archive manager
    - gnome-logs # Gnome systemd journalctl viewer
    - gnome-disk-utility
  files:
    - qimgv # Lightweight image viewer
    - vlc
    - shotcut # video editor
  browser:
    - google-chrome-stable
  gaming:
    - dolphin-emu
  misc:
    - fonts-noto-color-emoji # adds emoji support in fonts    