user:
    # VS Code extension names can be listed by running `code --list-extensions`
    # and be placed here to be installed with `code --install-extension EXTENSION_NAME` 
  vscode_extensions:
    - akamud.vscode-theme-onedark
    - james-yu.latex-workshop
    - streetsidesoftware.code-spell-checker
    - ms-python.python
    - ms-python.debugpy
    - ms-python.isort
    - ms-python.vscode-pylance
    - ms-vscode.cpptools
    - ms-vscode.cpptools-extension-pack
    - ms-vscode.cpptools-themes
    - ms-vscode.cmake-tools
    - redhat.ansible
    - redhat.vscode-yaml
  
  chrome_extensions:
    - extension_id: ddkjiahejlhfcafbddmgiahcphecmpfh
      extension_name: 'uBlock Origin Lite'
  
  profile_picture: 'kazuha.png'