---
- name: Create a tmp directory
  ansible.builtin.file:
    path: ./tmp
    state: directory

- name: Download IntelliJ Idea package to tmp directory
  ansible.builtin.shell:
    cmd: wget --no-check-certificate {{ intellij_download_url }}
  args:
    chdir: ./tmp
  no_log: true

- name: Register IntelliJ Idea package name
  ansible.builtin.shell:
    cmd: ls . | grep idea.*\.tar\.gz
  register: idea_filename
  args:
    chdir: ./tmp

- name: Unarchive IntelliJ package to /usr/local
  ansible.builtin.unarchive:
    src: ./tmp/{{ idea_filename.stdout }}
    dest: /usr/local
  become: true

- name: Register IntelliJ Idea folder name
  ansible.builtin.shell:
    cmd: ls -d */ | grep idea
  register: idea_foldername
  args:
    chdir: /usr/local

- name: Check if IntelliJ bin folder is in user .env PATH
  ansible.builtin.lineinfile:
    state: absent
    path: ~/.env
    regexp: "^export PATH=\\$PATH:/usr/local/{{ idea_foldername.stdout }}/bin"
  check_mode: true
  register: intellij_path_check

- name: Add IntelliJ bin folder to user .env PATH if not present
  ansible.builtin.lineinfile:
    state: present
    path: ~/.env
    line: export PATH=$PATH:/usr/local/{{ idea_foldername.stdout }}/bin
  when: intellij_path_check.found == 0

# IntelliJ can be run by executing `idea` in a shell. (Requires a new terminal session)