---
- name: Create a tmp directory
  ansible.builtin.file:
    path: ./tmp
    state: directory

- name: Download IntelliJ Idea package to tmp directory
  ansible.builtin.shell:
    cmd: wget {{ intellij_download_url }}
  args:
    chdir: ./tmp
  no_log: true

- name: Register IntelliJ Idea package name
  ansible.builtin.shell:
    cmd: ls . | grep idea 
  register: idea_filename
  args:
    chdir: ./tmp

- name: Unarchive IntelliJ package
  ansible.builtin.unarchive:
    src: ./tmp/{{ idea_filename.stdout }}
    dest: ./tmp

- name: Register IntelliJ Idea folder name
  ansible.builtin.shell:
    cmd: ls -d */ | grep idea 
  register: idea_foldername
  args:
    chdir: ./tmp

- name: Move IntelliJ folder to /usr/local
  ansible.builtin.copy:
    src: ./tmp/{{ idea_foldername.stdout }}/
    dest: /usr/local/{{ idea_foldername.stdout }}/
  become: true

- name: Check if IntelliJ bin folder is in user .env PATH
  ansible.builtin.lineinfile:
    state: absent
    path: ~/.env
    regexp: "^export PATH=$PATH:/usr/local/{{ idea_foldername.stdout }}/bin"
  check_mode: true
  changed_when: false
  register: intellij_path_check

- name: Add IntelliJ bin folder to user .env PATH if not present
  ansible.builtin.lineinfile:
    state: present
    path: ~/.env
    line: export PATH=$PATH:/usr/local/{{ idea_foldername.stdout }}/bin
  when: intellij_path_check.found == 0

# IntelliJ can now be run with bash ./tmp/{{ idea_foldername }}/bin/idea.sh