---
- name: Check if post MikTeX installation already finished
  ansible.builtin.shell:
    cmd: cat /var/lib/miktex-texmf/miktex/config/miktex.ini 2> /dev/null | grep 'AutoInstall=1' | wc -l
  become: true
  register: miktex_finish_check
  changed_when: false

- name: End miktex role if post MikTeX installation already finished
  ansible.builtin.meta: end_role
  when: miktex_finish_check.stdout | length > 0

- name: Ensure Perl and Miktex are installed
  ansible.builtin.apt:
    name: "{{ item }}"
    state: present
  become: true
  loop:
    - perl
    - miktex
  
- name: Finish system wide post Miktex installation
  ansible.builtin.shell: 
    cmd: miktexsetup --shared=yes finish
  become: true

- name: Enable Miktek automatic package installation
  ansible.builtin.shell:
    cmd: initexmf --admin --set-config-value [MPM]AutoInstall=1
  become: true