---
- name: Register Chrome absolute path
  ansible.builtin.shell:
    cmd: which google-chrome
  register: chrome_path

- name: Copy Photopea icon
  ansible.builtin.copy:
    src: ./files/photopea.png
    dest: /usr/share/applications/photopea.png
  become: true

- name: Add Photopea as a Progressive Web App (PWA) in a .desktop file
  ansible.builtin.template:
    src: ./templates/photopea.desktop.j2
    dest: /usr/share/applications/photopea.desktop
  vars:
    chrome_absolute_path: "{{ chrome_path.stdout }}"
    photopea_icon_path: /usr/share/applications/photopea.png
  become: true
  