---
# MOP found at https://cran.r-project.org
- name: Install R from apt if needed
  ansible.builtin.apt:
    name: r-base
    state: present
  become: true

- name: Check if R-Studio is already installed
  ansible.builtin.shell:
    cmd: which rstudio | wc -c
  register: rstudio_installed_check
  changed_when: false

- name: End rstudio role if R-Studio is installed
  ansible.builtin.meta: end_role
  when: rstudio_installed_check.stdout | int > 0

- name: Create a tmp directory
  ansible.builtin.file:
    path: ./tmp
    state: directory

- name: Download R-Studio package to tmp directory
  ansible.builtin.shell:
    cmd: wget --no-check-certificate {{ rstudio_download_url }}
  args:
    chdir: ./tmp
  no_log: true

- name: Register R-Studio package name
  ansible.builtin.shell:
    cmd: ls . | grep rstudio.*\.tar\.gz
  register: rstudio_filename
  args:
    chdir: ./tmp

- name: Unarchive R-Studio package to /usr/local
  ansible.builtin.unarchive:
    src: ./tmp/{{ rstudio_filename.stdout }}
    dest: /usr/local
  become: true

- name: Register R-Studio folder name
  ansible.builtin.shell:
    cmd: ls -d */ | grep rstudio | head -n 1
  register: rstudio_foldername
  args:
    chdir: /usr/local

- name: Add R-Studio folder to user .bashrc PATH if not present
  ansible.builtin.lineinfile:
    state: present
    path: ~/.bashrc
    line: export PATH=$PATH:/usr/local/{{ rstudio_foldername.stdout }}
    regexp: "^export PATH=\\$PATH:/usr/local/{{ rstudio_foldername.stdout }}"
    insertafter: '^# USER VARIABLES BEGIN'

- name: Add R-Studio .desktop file 
  ansible.builtin.template:
    src: ./templates/rstudio.desktop.j2
    dest: /usr/share/applications/rstudio.desktop
  vars:
    rstudio_absolute_path: /usr/local/{{ rstudio_foldername.stdout }}
  # automatically registers the .dekstop file as trusted. Otherwise, needs executable permissions
  become: true