---
# Method of Procedure (MOP) outlined here, https://www.tug.org/texlive/quickinstall.html
- name: Create a tmp directory
  ansible.builtin.file:
    path: ./tmp
    state: directory

- name: Download the latest texlive package to tmp directory
  ansible.builtin.shell: 
    cmd: wget https://mirror.ctan.org/systems/texlive/tlnet/install-tl-unx.tar.gz
  args: 
    chdir: ./tmp

- name: Extract texlive package
  ansible.builtin.shell: 
    cmd: zcat < install-tl-unx.tar.gz | tar xf /dev/stdin
  args: 
    chdir: ./tmp

- name: Ensure perl is installed
  ansible.builtin.apt:
    name: perl
    state: present
  become: true

- name: Register texlive folder name
  ansible.builtin.shell: 
    cmd: ls . | grep install-tl-2*
  register: texlive_folder_name
  args:
    chdir: ./tmp

- name: Install texlive (may take several hours)
  ansible.builtin.shell:
    cmd: perl ./install-tl --no-interaction 
  become: true
  args:
    chdir: "./tmp/{{ texlive_folder_name.stdout }}"