---
- name: Copy over all items inside fonts to the usr fonts folder
  ansible.builtin.copy:
    src: './files/fonts/'
    dest: '/usr/local/share/fonts/'
  become: true

- name: Install Google Noto Color Emoji for emoji support in fonts
  ansible.builtin.apt:
    name: fonts-noto-color-emoji
    state: present
  become: true

- name: Force reload font cache
  ansible.builtin.command: fc-cache -f -v
  become: true
  no_log: true
  changed_when: false
