---
- name: Verify that VS code is installed
  ansible.builtin.apt:
    name: code
    state: present
  become: true

- name: Install VS code extensions
  ansible.builtin.command: code --install-extension "{{ item }}"
  loop: "{{ vscode_extensions }}"
  when: "vscode_extensions is defined"

- name: Copy user settings.json for VS code
  ansible.builtin.copy:
    src: "./files/vscode-settings-final.json"
    dest: "~/.config/Code/User/settings.json"

- name: Copy user keybindings.json for VS code
  ansible.builtin.copy:
    src: "./files/vscode-keybindings-final.json"
    dest: "~/.config/Code/User/keybindings.json"
