---
- name: Add GPG keys
  ansible.builtin.shell:
    cmd: > 
      curl {{ item.gpg_key_url }} | 
      gpg --dearmor | 
      sudo tee /usr/share/keyrings/{{ item.keyring_name }}.gpg > /dev/null
  become: true

- name: Register architechture version
  ansible.builtin.shell:
    cmd: dpkg --print-architecture
  register: arch

- name: Add apt repository source
  ansible.builtin.shell:
    cmd: > 
      echo 'deb [arch={{ arch.stdout }}
      signed-by=/usr/share/keyrings/{{ item.keyring_name }}.gpg] {{ item.apt_repo_url }} stable main' |
      sudo tee /etc/apt/sources.list.d/{{ item.package_name }}.list
  become: true
