# dconf settings for blur-my-shell gnome extension
# can be loaded with dconf load /org/gnome/shell/extensions/blur-my-shell/ < blur-my-shell.ini
[/]
brightness=0.84999999999999998
color-and-noise=true
noise-amount=0.050000000000000003
noise-lightness=0.0
sigma=20

[applications]
blur=false
enable-all=false
opacity=230
whitelist=@as []

[dash-to-panel]
blur-original-panel=true

[hidetopbar]
compatibility=false

[overview]
blur=true
style-components=2

[panel]
blur=true
override-background=false
static-blur=true
unblur-in-overview=true
