---
# MOP: https://wiki.debian.org/Steam
- name: Ensure software-properties-common is installed
  ansible.builtin.apt:
    name: software-properties-common
    state: present
  become: true

# Avoids doing manual line checks and writes to sources list: https://linuxcapable.com/how-to-enable-contrib-and-non-free-repos-on-debian-linux/
- name: Enable contrib and non-free-firmware for Debian apt sources
  ansible.builtin.shell:
    cmd: apt-add-repository contrib non-free-firmware
  become: true

- name: Enable Multi-Arch for amd64 systems
  ansible.builtin.shell:
    cmd: dpkg --add-architecture i386
  become: true

- name: Update apt cache
  ansible.builtin.apt:
    update_cache: true
  become: true

- name: Get the Steam installer
  ansible.builtin.apt:
    name: steam-installer
    state: present
  become: true

- name: Install additional libraries for Vulkan and 32-bit titles
  ansible.builtin.apt:
    name: "{{ item }}"
    state: present
  become: true
  loop:
    - mesa-vulkan-drivers
    - libglx-mesa0:i386
    - mesa-vulkan-drivers:i386
    - libgl1-mesa-dri:i386
