---
- name: Change Nautilus preferences
  ansible.builtin.shell:
    cmd: dconf write /org/gnome/nautilus/preferences/{{ item.key }} \"{{ item.value }}\"
  loop:
    - key: default-folder-viewer
      value: "'list-view'"
    - key: search-filter-time-type
      value: "'last_modified'"

- name: Change Nautilus list view
  ansible.builtin.shell:
    cmd: dconf write /org/gnome/nautilus/list-view/default-zoom-level \"'small'\"

- name: Copy Nautlius Templates folder to user home directory
  ansible.builtin.copy:
    src: ./roles/gsettings/files/nautilus_templates/
    dest: ~/Templates