---
# MOP: https://wiki.debian.org/NvidiaGraphicsDrivers
- name: Determine if Nvidia GPU is present
  ansible.builtin.shell:
    cmd: lspci -nn | egrep -i '3d|display|vga' | grep -i 'NVIDIA' | wc -c
  register: nvidia_gpu_check

- name: End nvidia_driver role if Nvidia GPU is not present
  ansible.builtin.meta: end_role
  when: nvidia_gpu_check.stdout | int == 0

- name: Nvidia Wayland post-installation check
  block:
    - name: Check if Nvidia Wayland post-installation configuration is required
      ansible.builtin.shell:
        cmd: cat /sys/module/nvidia_drm/parameters/modeset
      register: nvidia_drm_kernel_modeset
      become: true
      ignore_errors: true
    
    - name: End install_nvidia_driver role if Nvidia Wayland post-installation is already done 
      ansible.builtin.meta: end_role
      when:
        - not nvidia_drm_kernel_modeset.failed
        - nvidia_drm_kernel_modeset.stdout | lower == 'y'

# Continue on with main installation
- name: Ensure mokutil is installed
  ansible.builtin.apt:
    name: mokutil
    state: present
  become: true

- name: Check if SecureBoot is enabled
  ansible.builtin.shell:
    cmd: mokutil --sb-state 2> /dev/null | grep -i enabled | wc -c
  become: true
  register: secureboot_enabled_check

- name: Fail if SecureBoot is enabled and MOK is not enrolled
  ansible.builtin.fail:
    msg: | 
      Ensure that your machine owner's key (MOK) is enrolled before installing Nvidia drivers. 

      Check https://wiki.debian.org/NvidiaGraphicsDrivers and https://wiki.debian.org/SecureBoot for instructions

      After completing, edit playbook_vars/gaming_vars.yml by setting the field gaming_vars.nvidia_drivers.bypass_secureboot_fail_reason to 'mok_enrolled' to continue installation of Nvidia drivers.
  when: 
    - secureboot_enabled_check | int > 0
    - gaming_vars.nvidia_drivers.bypass_secureboot_fail_reason is defined
    - gaming_vars.nvidia_drivers.bypass_secureboot_fail_reason == 'mok_enrolled'

- name: Check if contrib, non-free, and non-free-firmware is enabled in Debian apt sources
  ansible.builtin.shell:
    # The regex patterns used below match entries of this form:
      # deb http://deb.debian.org/debian/ bookworm main contrib non-free non-free-firmware
      # deb-src http://deb.debian.org/debian/ bookworm main contrib non-free non-free-firmware
      # deb http://security.debian.org/debian-security bookworm-security main contrib non-free non-free-firmware
      # deb-src http://security.debian.org/debian-security bookworm-security main contrib non-free non-free-firmware
      # deb http://deb.debian.org/debian/ bookworm-updates main contrib non-free non-free-firmware
      # deb-src http://deb.debian.org/debian/ bookworm-updates main contrib non-free non-free-firmware
    cmd: >
      cat /etc/apt/sources.list | grep -v '^#' | grep -iq '^deb.* {{ ansible_distribution_release | lower }}[^ ]* .*contrib' &&
      cat /etc/apt/sources.list | grep -v '^#' | grep -iq '^deb.* {{ ansible_distribution_release | lower }}[^ ]* .*non-free' &&
      cat /etc/apt/sources.list | grep -v '^#' | grep -iq '^deb.* {{ ansible_distribution_release | lower }}[^ ]* .*non-free-firmware'
  register: contrib_enabled_check
  ignore_errors: true
  become: true

- name: Enable contrib, non-free, and non-free-firmware for Debian apt sources if needed
  block:
    - name: Register current deb sources
      ansible.builtin.shell:
        cmd: cat /etc/apt/sources.list | grep -v '^#' | grep -io '^deb.* {{ ansible_distribution_release | lower }}[^ ]*'
      register: deb_sources
      become: true

    - name: Remove current deb sources
      ansible.builtin.lineinfile:
        state: absent
        regexp: "{{ item }}"
        path: /etc/apt/sources.list
      loop: "{{ deb_sources.stdout_lines }}"
      become: true
    
    - name: Re-add deb sources with main, contrib, non-free, and non-free-firmware
      ansible.builtin.lineinfile:
        state: present
        line: "{{ item }} main contrib non-free non-free-firmware"
        path: /etc/apt/sources.list
      loop: "{{ deb_sources.stdout_lines }}"
      become: true

    - name: Enable Multi-Arch for amd64 systems
      ansible.builtin.shell:
        cmd: dpkg --add-architecture i386
      become: true

  when: contrib_enabled_check is failed

- name: Update apt cache
  ansible.builtin.apt:
    update_cache: true
  become: true

- name: Uninstall any previous Nvidia drivers
  ansible.builtin.apt:
    name: '*nvidia*'
    state: absent
  become: true

- name: Remove dependencies that are no longer required and purge their configuration files
  ansible.builtin.apt:
    autoremove: true
    purge: true
  become: true

- name: Install Nvidia drivers
  ansible.builtin.apt:
    name: "{{ item }}"
    state: present
  become: true
  loop:
    # I've found that this nvidia open DKMS kernel module "breaks" the driver installation after rebooting
    # I will note that it was with SecureBoot disabled during my time testing
    # I have a hunch that SecureBoot needs to be ENABLED for this nvidia open kernel dkms module to work

    # Thanks to these two poor souls for the somewhat obscure insight: 
    # -- https://superuser.com/questions/1604967/
    # -- how-to-fix-nvidia-current-not-found-after-modprobe https://www.reddit.com/r/debian/s/TWMFyh6Usj

    # - nvidia-open-kernel-dkms   -- hence, I have commented this out for now 
    - nvidia-driver
    - firmware-misc-nonfree

- name: Reboot system for Nvidia drivers to take affect
  ansible.builtin.shell:
    cmd: |
      echo 'Rebooting in 10s for Nvidia drivers to take effect...'
      sleep 10 && reboot
  become: true