---
# MOP: https://wiki.debian.org/NvidiaGraphicsDrivers
- name: Determine if Nvidia GPU is present
  ansible.builtin.shell:
    cmd: lspci -nn | egrep -i '3d|display|vga' | grep -i 'NVIDIA' | wc -c
  register: nvidia_gpu_check

- name: End nvidia_driver role if Nvidia GPU is not present
  ansible.builtin.meta: end_role
  when: nvidia_gpu_check.stdout | int == 0

- name: Nvidia Wayland post-installation
  block:
    - name: Check if Nvidia Wayland post-installation configuration is required
      ansible.builtin.shell:
        cmd: cat /sys/module/nvidia_drm/parameters/modeset
      register: nvidia_drm_kernel_modeset
      become: true
      ignore_errors: true
    
    - name: End nvidia_driver role if Nvidia Wayland post-installation is already done 
      ansible.builtin.meta: end_role
      when:
        - not nvidia_drm_kernel_modeset.failed
        - nvidia_drm_kernel_modeset.stdout | lower == 'y'
    
    - name: Do Nvidia Wayland post-installation
      ansible.builtin.lineinfile:
        path: /etc/modprobe.d/nvidia-options.conf
        state: present
        line: options nvidia-drm modeset=1
      become: true
      when: 
        - not nvidia_drm_kernel_modeset.failed
        - nvidia_drm_kernel_modeset.stdout | lower == 'n'

    - name: Reboot system for Nvidia Wayland post-installation
      ansible.builtin.shell:
        cmd: |
          echo 'Rebooting in 10s for Nvidia Wayland post-installation to take effect...'
          sleep 10 && reboot
      become: true

# Continue on with main installation
- name: Ensure mokutil is installed
  ansible.builtin.apt:
    name: mokutil
    state: present
  become: true

- name: Check if SecureBoot is enabled
  ansible.builtin.shell:
    cmd: mokutil --sb-state 2> /dev/null | grep -i enabled | wc -c
  become: true
  register: secureboot_enabled_check

- name: Fail if SecureBoot is enabled and MOK is not enrolled
  ansible.builtin.fail:
    msg: | 
      Ensure that your machine owner's key (MOK) is enrolled before installing Nvidia drivers. 

      Check https://wiki.debian.org/NvidiaGraphicsDrivers and https://wiki.debian.org/SecureBoot for instructions

      After completing, edit your localhost.yml to set the field gaming.nvidia_drivers.bypass_secureboot_fail_reason to 'mok_enrolled' to continue installation of Nvidia drivers.
  when: 
    - secureboot_enabled_check | int > 0
    - bypass_secureboot_fail_reason is defined
    - bypass_secureboot_fail_reason == 'mok_enrolled'

- name: Check if contrib, non-free, and non-free-firmware is enabled in Debian apt sources
  ansible.builtin.shell:
    cmd: cat /etc/apt/sources.list | grep -v '^#' | grep -i 'non-free' | wc -l
  register: contrib_enabled_check
  become: true

# Just a quick easy way to avoid additional Ansible tasks 
# to write to the sources list manually: https://linuxcapable.com/how-to-enable-contrib-and-non-free-repos-on-debian-linux/
- name: Enable contrib, non-free, and non-free-firmware for Debian apt sources
  ansible.builtin.shell:
    cmd: apt-add-repository -y contrib non-free non-free-firmware 
  become: true
  when: contrib_enabled_check.stdout | int == 0

- name: Update apt cache
  ansible.builtin.apt:
    update_cache: true
  become: true

- name: Uninstall any previous Nvidia drivers
  ansible.builtin.apt:
    name: '*nvidia*'
    state: absent
  become: true

- name: Remove dependencies that are no longer required and purge their configuration files
  ansible.builtin.apt:
    autoremove: true
    purge: true
  become: true

- name: Install Nvidia drivers
  ansible.builtin.apt:
    name: "{{ item }}"
    state: present
  become: true
  loop:
    # I've found that this nvidia open DKMS kernel module "breaks" the driver installation after rebooting, and I will note that it was with SecureBoot disabled during my time testing

    # I have a hunch that SecureBoot needs to be ENABLED for this nvidia open kernel dkms module to work

    # Thanks to these two poor souls for the somewhat obscure insight: 
    # -- https://superuser.com/questions/1604967/
    # -- how-to-fix-nvidia-current-not-found-after-modprobe https://www.reddit.com/r/debian/s/TWMFyh6Usj

    # - nvidia-open-kernel-dkms 
    - nvidia-driver
    - firmware-misc-nonfree

- name: Reboot system for Nvidia drivers to take affect
  ansible.builtin.shell:
    cmd: |
      echo 'Rebooting in 10s for Nvidia drivers to take effect...'
      sleep 10 && reboot
  become: true