---
# MOP: https://wiki.debian.org/Steam
- name: Check if Steam is already installed and configured by checking if 'false' is written to the Steam install script
  ansible.builtin.shell:
    cmd: cat $(which steam || echo '.') 2> /dev/null | grep 'false' | wc -c
  register: steam_installed_check

- name: End steam role if Steam is already installed and configured
  ansible.builtin.meta: end_role
  when: steam_installed_check.stdout | int > 0

- name: Check if contrib, non-free, and non-free-firmware is enabled in Debian apt sources
  ansible.builtin.shell:
    # The regex patterns used below match entries of this form:
      # deb http://deb.debian.org/debian/ bookworm main contrib non-free non-free-firmware
      # deb-src http://deb.debian.org/debian/ bookworm main contrib non-free non-free-firmware
      # deb http://security.debian.org/debian-security bookworm-security main contrib non-free non-free-firmware
      # deb-src http://security.debian.org/debian-security bookworm-security main contrib non-free non-free-firmware
      # deb http://deb.debian.org/debian/ bookworm-updates main contrib non-free non-free-firmware
      # deb-src http://deb.debian.org/debian/ bookworm-updates main contrib non-free non-free-firmware
    cmd: >
      cat /etc/apt/sources.list | grep -v '^#' | grep -iq '^deb.* {{ ansible_distribution_release | lower }}[^ ]* .*contrib' &&
      cat /etc/apt/sources.list | grep -v '^#' | grep -iq '^deb.* {{ ansible_distribution_release | lower }}[^ ]* .*non-free' &&
      cat /etc/apt/sources.list | grep -v '^#' | grep -iq '^deb.* {{ ansible_distribution_release | lower }}[^ ]* .*non-free-firmware'
  register: contrib_enabled_check
  ignore_errors: true
  become: true

- name: Enable contrib, non-free, and non-free-firmware for Debian apt sources if needed
  block:
    - name: Register current deb sources
      ansible.builtin.shell:
        cmd: cat /etc/apt/sources.list | grep -v '^#' | grep -io '^deb.* {{ ansible_distribution_release | lower }}[^ ]*'
      register: deb_sources
      become: true

    - name: Remove current deb sources
      ansible.builtin.lineinfile:
        state: absent
        regexp: "{{ item }}"
        path: /etc/apt/sources.list
      loop: "{{ deb_sources.stdout_lines }}"
      become: true
    
    - name: Re-add deb sources with main, contrib, non-free, and non-free-firmware
      ansible.builtin.lineinfile:
        state: present
        line: "{{ item }} main contrib non-free non-free-firmware"
        path: /etc/apt/sources.list
      loop: "{{ deb_sources.stdout_lines }}"
      become: true

    - name: Enable Multi-Arch for amd64 systems
      ansible.builtin.shell:
        cmd: dpkg --add-architecture i386
      become: true

  when: contrib_enabled_check is failed

- name: Update apt cache
  ansible.builtin.apt:
    update_cache: true
  become: true

- name: Get the Steam installer
  ansible.builtin.apt:
    name: steam-installer
    state: present
  become: true

- name: Install additional libraries for Vulkan and 32-bit titles
  ansible.builtin.apt:
    name: "{{ item }}"
    state: present
  become: true
  loop:
    - mesa-vulkan-drivers
    - libglx-mesa0:i386
    - mesa-vulkan-drivers:i386
    - libgl1-mesa-dri:i386

- name: Register Steam installer script location
  ansible.builtin.shell:
    cmd: which steam
  register: steam_install_location

- name: Bypass Zenity GUI installation prompt in the Steam installer
  ansible.builtin.lineinfile:
    path: "{{ steam_install_location.stdout }}"
    line: 'if false && ! "$zenityish" \'
    regexp: 'if ! "\$zenityish"'
  become: true

- name: Install Steam using the steam-installer
  ansible.builtin.shell:
    cmd: steam
