---
- name: Copy files in gnome_icons to /usr/share/icons
  ansible.builtin.copy:
    src: "{{ role_path }}/files/gnome_icons/"
    dest: /usr/share/icons/
  become: true

- name: Find any tar files to unarchive
  ansible.builtin.find:
    paths: /usr/share/icons
    patterns: '*.tar*'
    recurse: false
  register: tar_files

- name: Unarchive each tar file
  ansible.builtin.unarchive:
    src: "{{ item.path }}"
    dest: /usr/share/icons/
  loop: "{{ tar_files.files }}"
  loop_control:
    label: "{{ item.path }}"
  become: true

- name: Set default icon theme
  ansible.builtin.shell:
    cmd: dconf write /org/gnome/desktop/interface/icon-theme "'{{ icon_theme | default('Adwaita', true) }}'"
