# dconf settings for openweather gnome extension
# can be loaded with dconf load /org/gnome/shell/extensions/openweather/ < openweather.ini 
[/]
city='43.6534817,-79.3839347>Waterloo, Canada>0'
menu-alignment=56.81818181818182
position-in-panel='left'
show-comment-in-panel=true
use-system-icons=true
wind-direction=false
