---
ansible_connection: local

gpg_keys_to_install:
- gpg_key_url: https://packages.microsoft.com/keys/microsoft.asc
  keyring_name: microsoft-archive-keyring
  apt_repo_url: https://packages.microsoft.com/repos/code
  sources_list_name: vscode
  package_name: code

apt_packages_to_install:
- curl
- wget
- git
- bash-completion
- python3
- nodejs
- npm
- default-jdk
