---
ansible_connection: local

gpg_keys_to_install:
- gpg_key_url: https://packages.microsoft.com/keys/microsoft.asc
  keyring_name: microsoft-archive-keyring
  apt_repo_url: https://packages.microsoft.com/code
  package_name: vscode

apt_packages_to_install:
- curl
- wget
- git
- python3