---
ansible_connection: local

# Used for adding apt repos and their signing keys if a package cannot be found in existing apt repositories
apt_repos_to_add:
- package_name: code 
  key_url: https://packages.microsoft.com/keys/microsoft.asc
  key_filename: microsoft-archive-keyring.asc
  apt_repo_url: https://packages.microsoft.com/repos/code
  source_list_name: vscode
  sources_list_suite_name: stable
  sources_list_components: main

- package_name: miktex 
  key_url: https://miktex.org/download/key
  key_filename: miktex.asc
  apt_repo_url: https://miktex.org/download/debian
  source_list_name: miktex
  sources_list_suite_name: ''       # defaults to ansible_distribution_release
  sources_list_components: universe

# Remove any pre-installed apt pacakges
apt_packages_to_remove:
- gnome-games
- libreoffice*

# Install user apt packages
apt_packages_to_install:
- curl
- wget
- bash-completion
- linux-headers-amd64 # needed for future driver installations
- git
- perl # needed for miktex to install
- code
- miktex
- python3
- nautilus # files app
- nautilus-extension-gnome-terminal # adds show in terminal context menu
- gnome-text-editor
- chromium
- nodejs
- npm
- shotcut # video editor

# VS Code extension names can be listed by running `code --list-extensions` and 
# be placed here to be installed with `code --install-extension EXTENSION_NAME` 
vscode_extensions:
- akamud.vscode-theme-onedark
- james-yu.latex-workshop
- streetsidesoftware.code-spell-checker
- ms-python.debugpy
- ms-python.isort
- ms-python.python
- ms-python.vscode-pylance
- ms-vscode.cpptools
- ms-vscode.cpptools-extension-pack
- ms-vscode.cpptools-themes
- ms-vscode.cmake-tools
- redhat.ansible
- redhat.vscode-yaml

gnome_keyboard_shortcuts:
- name: Terminal
  binding: <Control><Alt>t
  command: gnome-terminal

- name: Flameshot
  binding: Print
  command: flameshot gui

desktop:
  wallpaper_filename: space-gooose-spacehawks.jpg
  screensaver_filename: space-gooose-spacehawks.jpg
  preferDarkTheme: true

favorite_apps:
  - org.gnome.Terminal.desktop
  - code.desktop
  - org.gnome.Nautilus.desktop
  - chromium.desktop