---
- name: Playbook for apt setup (add repos, remove and install packages)
  hosts: localhost
  vars_files:
    - ./playbook_vars/apt_vars.yml
    - ./playbook_vars/apt_packages_list_vars.yml

  tasks:
    - name: Update apt repositories
      ansible.builtin.apt:
        update_cache: true
      become: true

    - name: Remove pre-installed apt packages and its dependencies
      ansible.builtin.apt:
        name: "{{ item }}"
        state: absent
        purge: true
        autoremove: true
      become: true
      loop: "{{ apt_vars.packages_to_remove | default([], true) }}"

    - name: Add user apt repos
      ansible.builtin.include_role:
        name: apt
        tasks_from: add_apt_repos
      loop: "{{ apt_vars.add_apt_repos }}"
      loop_control:
        label: "{{ item.package_name }}"

    - name: Update apt repositories after adding user apt repos
      ansible.builtin.apt:
        update_cache: true
      become: true

    - name: Install some lists of apt packages
      ansible.builtin.include_role:
        name: apt
        tasks_from: install_apt_package_list
      loop:
        - "{{ apt_packages_list_vars.core }}"
        - "{{ apt_packages_list_vars.programming }}"
        - "{{ apt_packages_list_vars.files }}"
        - "{{ apt_packages_list_vars.browser }}"
        - "{{ apt_packages_list_vars.misc }}"
      loop_control:
        loop_var: package_list