---
- name: Example
  hosts: localhost

  tasks:
    - name: Debug
      ansible.builtin.debug:
        msg: "test"
    - name: Invoke role
      ansible.builtin.include_role:
        name: apt
        tasks_from: install_packages
      vars: 
        packages_list: "{{ hostvars.localhost.apt_packages_to_install }}"