---
- name: Playbook to add apt repos and install apt packages
  hosts: localhost

  tasks:
    - name: Update apt repositories
      ansible.builtin.apt:
        update_cache: true
      become: true

    - name: Add apt repos
      ansible.builtin.include_role:
        name: apt
        tasks_from: add_apt
      loop: "{{ hostvars.localhost.apt_repos_to_add }}"
      loop_control:
        label: "{{ item.package_name }}"

    - name: Update apt repositories after adding apt repos
      ansible.builtin.apt:
        update_cache: true
      become: true

    - name: Install apt packages
      ansible.builtin.apt:
        name: "{{ item }}"
        state: present
      loop: "{{ hostvars.localhost.apt_packages_to_install }}"
      loop_control: 
        label: "{{ item }}"
      become: true