---
- name: Playbook for apt setup (add repos, remove and install packages)
  hosts: localhost

  tasks:
    - name: Update apt repositories
      ansible.builtin.apt:
        update_cache: true
      become: true

    - name: Remove pre-installed apt packages and its dependencies
      ansible.builtin.apt:
        name: "{{ item }}"
        state: absent
        purge: true
        autoremove: true
      become: true
      loop: "{{ hostvars.localhost.apt_packages_to_remove }}"

    - name: Add user apt repos
      ansible.builtin.include_role:
        name: apt
        tasks_from: add_apt
      loop: "{{ hostvars.localhost.apt_repos_to_add }}"
      loop_control:
        label: "{{ item.package_name }}"

    - name: Update apt repositories after adding user apt repos
      ansible.builtin.apt:
        update_cache: true
      become: true

    - name: Install user apt packages
      ansible.builtin.apt:
        name: "{{ item }}"
        state: present
      loop: "{{ hostvars.localhost.apt_packages_to_install | default([], true) }}"
      loop_control: 
        label: "{{ item }}"
      become: true