---
- name: Playbook to configure Gnome DE
  hosts: localhost

  tasks: 
    - name: Configure custom keyboard shortcuts
      block:
        # Hacky way to avoid duplicate entries if this gets re-run
        # A proper removal/reset would be dconf write KEY "@as []" which is done below. 
        # This just sets the KEY to an empty string "" instead of "@as []" for an empty array. But, the logic becomes nicer when we call the keyboard_shortcuts role
      - name: Reset custom shortcuts
        ansible.builtin.shell:
          cmd: dconf reset /org/gnome/settings-daemon/plugins/media-keys/custom-keybindings

        # We'll bind PrintScreen to Flameshot as a custom keyboard shortcut later instead
      - name: Disable default Gnome Screenshot PrintScreen shortcut
        ansible.builtin.shell:
          cmd: dconf write /org/gnome/shell/keybindings/show-screenshot-ui '@as []'

      - name: Add user-defined custom shortcuts
        ansible.builtin.include_role:
          name: gsettings
          tasks_from: keyboard_shortcuts
        loop: "{{ hostvars.localhost.gnome.keyboard_shortcuts }}"
        loop_control:
          index_var: index_var
          label: "{{ item.name }}"

    - name: Set user desktop preferences
      ansible.builtin.include_role:
        name: gsettings
        tasks_from: desktop
      vars:
        wallpaper_filename: "{{ hostvars.localhost.gnome.desktop.wallpaper_filename | default('') }}"
        screensaver_filename:  "{{ hostvars.localhost.gnome.desktop.screensaver_filename | default('') }}"
        prefer_dark_theme: "{{ hostvars.localhost.gnome.desktop.prefer_dark_theme | default(false) | bool }}"
        enable_hot_corners: "{{ hostvars.localhost.gnome.desktop.enable_hot_corners | default(true) | bool }}"
        clock: "{{ hostvars.localhost.gnome.desktop.clock }}"

    - name: Set user night light preferences
      ansible.builtin.include_role:
        name: gsettings
        tasks_from: night_light
      vars:
        night_light: "{{ hostvars.localhost.gnome.night_light }}"

    - name: Configure Nautilus preferences
      ansible.builtin.include_role:
        name: gsettings
        tasks_from: nautilus
    
    - name: Reset and set user favorite-apps
      block:
        - name: Reset favorite apps
          ansible.builtin.shell:
            cmd: dconf reset /org/gnome/shell/favorite-apps
            
        - name: Set user favorite-apps
          ansible.builtin.include_role:
            name: gsettings
            tasks_from: favorite_apps
          loop: "{{ hostvars.localhost.gnome.favorite_apps }}"
          when: hostvars.localhost.gnome.favorite_apps | default([], true) | length > 0

    - name: Finalize miscellaneous settings
      ansible.builtin.include_role:
        name: gsettings
        tasks_from: misc_settings  