---
- name: Playbook to configure Gnome DE
  hosts: localhost

  tasks: 
    - name: Add custom keyboard shortcuts
      block:
        # Hacky way to avoid duplicate entries if this gets re-run
        # A proper removal/reset would be dconf write KEY "@as []" which is done below. 
        # This just sets the KEY to an empty string "" instead of "@as []" for an empty array. But, the logic becomes nicer when we call the keyboard_shortcuts role
      - name: Reset custom shortcuts 
        ansible.builtin.shell:
          cmd: dconf reset /org/gnome/settings-daemon/plugins/media-keys/custom-keybindings

        # We'll bind PrintScreen to Flameshot as a custom keyboard shortcut later instead
      - name: Disable default Gnome Screenshot PrintScreen shortcut
        ansible.builtin.shell:
          cmd: dconf write /org/gnome/shell/keybindings/show-screenshot-ui '@as []'

      - name: Add custom shortcuts
        ansible.builtin.include_role:
          name: gsettings
          tasks_from: keyboard_shortcuts
        loop: "{{ hostvars.localhost.gnome_keyboard_shortcuts }}"
        loop_control:
          index_var: index_var
          label: "{{ item.name }}"

      - name: Set user desktop preferences
        ansible.builtin.include_role:
          name: gsettings
          tasks_from: desktop
        vars:
          wallpaper_filename: "{{ hostvars.localhost.desktop.wallpaper_filename | default('') }}"
          screensaver_filename:  "{{ hostvars.localhost.desktop.screensaver_filename | default('') }}"
          preferDarkTheme: "{{ hostvars.localhost.desktop.preferDarkTheme |default(false) | bool }}"
    