---
- name: Playbook to configure Gnome DE
  hosts: localhost

  tasks: 
    - name: Add custom keyboard shortcuts
      block:
        # Hacky way to avoid duplicate entries if this gets re-run
      - name: Reset any custom shortcuts 
        ansible.builtin.shell:
          cmd: dconf reset /org/gnome/settings-daemon/plugins/media-keys/custom-keybindings

      - name: Add custom shortcuts
        ansible.builtin.include_role:
          name: gsettings
          tasks_from: keyboard_shortcuts
        loop: "{{ hostvars.localhost.gnome_keyboard_shortcuts }}"
        loop_control:
          index_var: index_var
          label: "{{ item.name }}"
    