---
- name: Playbook to install user programs
  hosts: localhost
  vars_files:
    - ./playbook_vars/programs_vars.yml
    - ./playbook_vars/apt_packages_list_vars.yml

  tasks: 
    - name: Install programs apt packages
      ansible.builtin.include_role:
        name: apt
        tasks_from: install_apt_package_list
      loop:
        - "{{ apt_packages_list_vars.school }}"
      loop_control:
        loop_var: package_list
      when:
        - ansible_distribution_release | lower != 'trixie'

    - name: Install and configure IntelliJ Idea
      ansible.builtin.include_role:
        name: programs
        tasks_from: intellij
        apply:
          tags: ['gnome_intellij', 'intellij', 'idea']
      tags: ['programs_intellij', 'intellij', 'idea']

    - name: Install and configure Flameshot
      ansible.builtin.include_role:
        name: programs
        tasks_from: flameshot
        apply:
          tags: ['programs_flameshot', 'flameshot']
      tags: ['programs_flameshot', 'flameshot']
    
    - name: Install and configure OpenJDK
      ansible.builtin.include_role:
        name: programs
        tasks_from: openjdk
        apply:
          tags: ['programs_openjdk', 'openjdk', 'jdk', 'java']
      tags: ['programs_openjdk', 'openjdk', 'jdk', 'java']
    
    - name: Install and configure Docker
      ansible.builtin.include_role:
        name: programs
        tasks_from: docker
        apply:
          tags: ['programs_docker', 'docker']
      tags: ['programs_docker', 'docker']
    
    - name: Install R and R-Studio
      ansible.builtin.include_role:
        name: programs
        tasks_from: rstudio
        apply:
          tags: ['programs_r', 'programs_rstudio', 'r', 'rstudio']
      tags: ['programs_r', 'programs_rstudio', 'r', 'rstudio']

    - name: Add PhotoPea as a Progressive Web App (PWA)
      ansible.builtin.include_role:
        name: programs
        tasks_from: photopea
        apply:
          tags: ['programs_photopea', 'photopea', 'photoshop']
      tags: ['programs_photopea', 'photopea', 'photoshop']


    - name: Install TinyTex for LaTeX support on Trixie
      ansible.builtin.include_role:
        name: programs
        tasks_from: tinytex
        apply:
          tags: ['programs_tinytex', 'tinytex', 'latex']
      tags: ['programs_tinytex', 'tinytex', 'latex']
      when:
        - ansible_distribution_release | lower == 'trixie'

    - name: Install MikTeX for LaTeX support (not supported on Trixie yet)
      ansible.builtin.include_role:
        name: programs
        tasks_from: miktex
        apply:
          tags: ['programs_miktex', 'miktex', 'latex']
      tags: ['programs_miktex', 'miktex', 'latex']
      when:
        - ansible_distribution_release | lower != 'trixie'
