---
- name: Playbook to install user programs
  hosts: localhost
  vars_files:
    - ./playbook_vars/programs_vars.yml
    - ./playbook_vars/apt_packages_list.yml

  tasks: 
    - name: Install programs apt packages
      ansible.builtin.include_role:
        name: apt
        tasks_from: install_apt_packages_list
      loop:
        - "{{ apt_packages_list_vars.school }}"
      loop_control:
        loop_var: package_list

    - name: Install and configure IntelliJ Idea
      ansible.builtin.include_role:
        name: programs
        tasks_from: intellij

    - name: Install and configure Flameshot
      ansible.builtin.include_role:
        name: programs
        tasks_from: flameshot
    
    - name: Install and configure OpenJDK
      ansible.builtin.include_role:
        name: programs
        tasks_from: openjdk
    
    - name: Install R and R-Studio
      ansible.builtin.include_role:
        name: programs
        tasks_from: rstudio

    - name: Add PhotoPea as a Progressive Web App (PWA)
      ansible.builtin.include_role:
        name: programs
        tasks_from: photopea

    - name: Install MikTeX for LaTeX support
      ansible.builtin.include_role:
        name: programs
        tasks_from: miktex

