---
- name: Playbook to install user programs
  hosts: localhost

  tasks: 
    - name: Install and configure IntelliJ Idea
      ansible.builtin.include_role:
        name: programs
        tasks_from: intellij

    - name: Install and configure Flameshot
      ansible.builtin.include_role:
        name: programs
        tasks_from: flameshot
    
    - name: Install and configure OpenJDK
      ansible.builtin.include_role:
        name: programs
        tasks_from: OpenJDK
    
    - name: Install R and R-Studio
      ansible.builtin.include_role:
        name: programs
        tasks_from: rstudio

    - name: Add R PhotoPea as a Progressive Web App (PWA)
      ansible.builtin.include_role:
        name: programs
        tasks_from: photopea

    - name: Attempt to install TexLive for LaTeX support (may take hours)
      block:
        - name: Install TexLive
          ansible.builtin.include_role:
            name: programs
            tasks_from: texlive
          when: false
      rescue:
        - name: Remove failed TexLive installation
          ansible.builtin.file:
            path: /usr/local/texlive
            state: absent
    