---
- name: Test
  hosts: localhost

  tasks:
    - name: Install Gnome Extensions
      ansible.builtin.include_role:
        name: user
        tasks_from: install_gnome_extensions
      loop: "{{ hostvars.localhost.gnome.gnome_extensions }}"
