---
- name: Test
  hosts: localhost

  tasks:
    - name: Install Chromium extensions
      ansible.builtin.include_role:
        name: user
        tasks_from: chromium_extensions
      loop: "{{ hostvars.localhost.user.chromium_extensions | default([], true) }}"
      loop_control:
        label: item.extension_name