---
- name: Test
  hosts: localhost
  vars_files:
    - ./playbook_vars/gnome_vars.yml

  tasks:
    - name: Install and set default icons
      ansible.builtin.include_role:
        name: gnome
        tasks_from: icon.yml
      vars:
        icon_theme: "{{ gnome_vars.desktop.icon_theme }}"
    # - name: test
    #   ansible.builtin.include_role:
    #     name: gnome
    #     tasks_from: configure_gnome_extensions
    #   loop: "{{ gnome_vars.gnome_extensions }}"
