---
- name: Test
  hosts: localhost

  tasks:
    - name: Add user profile picture
      ansible.builtin.include_role:
        name: user
        tasks_from: profile_picture
      vars:
        profile_picture: "{{ hostvars.localhost.user.profile_picture | default('') }}"