---
- name: Test
  hosts: localhost

  tasks:
    - name: Install OpenJDK if not installed
      block:
        - name: Check if OpenJDK is already installed
          ansible.builtin.shell:
            cmd: which javac | wc -l
          register: openjdk_installed_check

        - name: Install OpenJDK
          ansible.builtin.include_role:
            name: programs
            tasks_from: openjdk
          when: openjdk_installed_check.stdout | int == 0
