---
- name: Test
  hosts: localhost

  tasks:
    - name: Test
      ansible.builtin.include_role:
        name: user
        tasks_from: vscode
      vars:
        vscode_extensions: "{{ hostvars.localhost.vscode_extensions }}"