---
- name: Test
  hosts: localhost

  tasks:
    - name: Test
      ansible.builtin.shell:
        cmd: dconf read /org/gnome/shell/app-picker-layout | tr -d '[]{}<>'
      register: my_arr
    - name: Debug
      ansible.builtin.debug:
        msg: "{{ my_arr.stdout | split(',') | sort }}"