---
- name: Test
  hosts: localhost

  tasks:
    - name: Set user desktop preferences
      ansible.builtin.include_role:
        name: gsettings
        tasks_from: desktop
      vars:
        wallpaper_filename: "{{ hostvars.localhost.desktop.wallpaper_filename | default('') }}"
        screensaver_filename:  "{{ hostvars.localhost.desktop.screensaver_filename | default('') }}"
        preferDarkTheme: "{{ hostvars.localhost.desktop.preferDarkTheme | default(false) | bool }}"
        
