---
- name: Playbook to setup user configurations
  hosts: localhost

  tasks:
    - name: Backup existing user bashrc and copy over an updated one
      ansible.builtin.include_role:
        name: user
        tasks_from: bashrc

    - name: Template and copy gitconfig to user home directory
      ansible.builtin.include_role:
        name: user
        tasks_from: gitconfig
      vars:
        GITHUB_USERNAME: "{{ hostvars.localhost.user.gitconfig.username }}"
        GITHUB_PAT: "{{ hostvars.localhost.user.gitconfig.pat }}"
        GITHUB_EMAIL: "{{ hostvars.localhost.user.gitconfig.email }}"

    - name: Add additional fonts
      ansible.builtin.include_role:
        name: user
        tasks_from: fonts

    - name: Add VS code extensions and settings
      ansible.builtin.include_role:
        name: user
        tasks_from: vscode
      vars:
        vscode_extensions: "{{ hostvars.localhost.user.vscode_extensions | default([], true) }}"
    
    - name: Install Chrome extensions
      ansible.builtin.include_role:
        name: user
        tasks_from: chrome_extensions
      loop: "{{ hostvars.localhost.user.chrome_extensions | default([], true) }}"
      loop_control:
        label: item.extension_name